#!/bin/bash
git config --global  user.name "gjacobk"
git config --global  user.email "unofficalrom@gmail.com"

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
# I want to sync aex source!
repo init -q --no-repo-verify --depth=1 -u repo init -u https://github.com/descendant-xi/manifests.git -b eleven-staging -g default,-device,-mips,-darwin,-notdefault

# Clone local manifest! So that no need to manually git clone repos or change hals, you can use normal git clone or rm and re clone, they will cost little more time, and you may get timeout! Let's make it quit and depth=1 too.
# My local manifest can do all clone, and removing or changing repository i need, so lets use it! I am lazy to manually git clone!
#git clone https://github.com/Apon77Lab/android_.repo_local_manifests.git --depth 1 -b aex .repo/local_manifests

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8

#device
git clone https://github.com/gjacobk/device_xiaomi_vince.git --single-branch -b des device/xiaomi/vince
git clone https://github.com/gjacobk/vendor_xiaomi_vince.git --single-branch -b derp-11 vendor/xiaomi/vince
git clone https://github.com/Blacksuan19/kernel_dark_ages_vince.git --single-branch -b darky kernel/xiaomi/vince
cd kernel/xiaomi/vince && git checkout darky && git revert fec013b9f5bb70c1e51285aa6e042f21f4298447 --no-edit && cd ../../..

#hals
rm -rf hardware/qcom-caf/msm8996/audio &&  git clone https://github.com/gjacobk/hardware_qcom_audio_msm8996-vince.git hardware/qcom-caf/msm8996/audio
rm -rf hardware/qcom-caf/msm8996/media && git clone https://github.com/gjacobk/hardware_qcom_media_msm8996-vince.git hardware/qcom-caf/msm8996/media
rm -rf hardware/qcom-caf/msm8996/display &&  https://github.com/gjacobk/hardware_qcom_display_msm8996-vince.git hardware/qcom-caf/msm8996/display
rm -rf hardware/qcom-caf/wlan && git clone https://android.googlesource.com/platform/hardware/qcom/wlan hardware/qcom-caf/wlan

